# Generated by Django 3.2.10 on 2023-08-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Mobile',
        ),
    ]
