# Generated by Django 3.2.10 on 2023-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230804_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmitdb',
            name='Uname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
