# Generated by Django 3.2.10 on 2023-08-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_usersubmitdb_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=500, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=150, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
