# Generated by Django 3.2.10 on 2023-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmitdb',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
