# Generated by Django 3.2.10 on 2023-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_usersubmitdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmitdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
