# Generated by Django 3.2.10 on 2023-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_usersubmitdb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmitdb',
            name='Modname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
