# Generated by Django 3.2.10 on 2023-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CModulesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewModule', models.CharField(blank=True, max_length=100, null=True)),
                ('Material', models.CharField(blank=True, max_length=100, null=True)),
                ('Files', models.FileField(max_length=250, upload_to='files')),
                ('Select', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
