# Generated by Django 3.2.10 on 2023-08-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_alter_lessondb_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessondb',
            old_name='ModName',
            new_name='SubName',
        ),
    ]
