# Generated by Django 3.2.10 on 2023-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_rename_modname_lessondb_subname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessondb',
            name='Attendance',
        ),
        migrations.AddField(
            model_name='lessondb',
            name='Study_m',
            field=models.FileField(blank=True, null=True, upload_to='Materials'),
        ),
    ]
